/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness — returns immediately. No DB or auth check.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness — validates DB connectivity + key tables exist.
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate by email + password, set the session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie. Idempotent: a
         *     request without a cookie still succeeds with status='ok'.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the logged-in user's identity.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description List candidates filtered by time window, status, kind.
         */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidate
         * @description Full candidate detail with rule trace, veto trace, llm evaluation,
         *     selected contract, and lifecycle events. Returns a single
         *     `copyable_text` block ready to paste into Claude.ai.
         */
        get: operations["get_candidate_api_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/full-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidate Full Context
         * @description Lightweight version of `GET /{candidate_id}` for the 'Copy Full
         *     Context' flow. Returns just the markdown block ready to paste into
         *     Claude.ai, without the structured payload. Useful when the caller
         *     has already fetched the structured detail and just wants the text.
         */
        get: operations["get_candidate_full_context_api_candidates__candidate_id__full_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Candidate
         * @description Transition pending_human_approval → approved. Idempotent (already
         *     approved → 200). Returns 409 if not in approvable state.
         */
        post: operations["approve_candidate_api_candidates__candidate_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Candidate
         * @description Transition pending_human_approval → rejected_by_user.
         */
        post: operations["reject_candidate_api_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description List positions filtered by status.
         */
        get: operations["list_positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Position Detail
         * @description Full position detail with lifecycle events + latest monitor evaluation
         *     + any pending exit candidate.
         */
        get: operations["get_position_detail_api_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Position Lifecycle
         * @description Lifecycle events for a position, newest first.
         */
        get: operations["list_position_lifecycle_api_positions__position_id__lifecycle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/scanner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scanner Evaluations
         * @description scanner_evaluations rows, newest first.
         */
        get: operations["list_scanner_evaluations_api_evaluations_scanner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Monitor Evaluations
         * @description monitor_evaluations rows, newest first.
         */
        get: operations["list_monitor_evaluations_api_evaluations_monitor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Llm Evaluations
         * @description llm_evaluations rows, newest first.
         */
        get: operations["list_llm_evaluations_api_evaluations_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_api_watchlist_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Today Or Date */
        put: operations["set_today_or_date_api_watchlist_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/tickers/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Ticker */
        post: operations["add_ticker_api_watchlist_tickers__ticker__post"];
        /** Remove Ticker */
        delete: operations["remove_ticker_api_watchlist_tickers__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_watchlist_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Universe */
        get: operations["list_universe_api_universe_get"];
        put?: never;
        /**
         * Add
         * @description Add one or more tickers. Idempotent.
         */
        post: operations["add_api_universe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove
         * @description Remove a ticker. Cascades to watchlists. Idempotent.
         */
        delete: operations["remove_api_universe__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the active strategy_configs.settings_json contents.
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings
         * @description Merge `updates` into the existing settings_json. Atomic.
         */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/prompts/{template_name}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show Active
         * @description Return the currently-active prompt for a template.
         */
        get: operations["show_active_api_prompts__template_name__active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{template_name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_prompts__template_name__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Pending
         * @description Create a new prompt version in 'pending' status. Activate via POST
         *     /api/prompts/activate to promote it (and demote the current active).
         */
        post: operations["create_pending_api_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate
         * @description Promote a pending or deprecated version → active. Demotes the
         *     previously-active row to deprecated. Atomic.
         */
        post: operations["activate_api_prompts_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{template_name}/rollback/{version_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback */
        post: operations["rollback_api_prompts__template_name__rollback__version_number__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Aggregated system state: toggles + queue depth + open positions
         *     + pending approvals + trading_mode + override_reasons.
         */
        get: operations["status__api_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Status
         * @description State of the market-data layer: which client is active and, for
         *     Schwab, the OAuth token expirations.
         *
         *     Phase 8a.5. Reads config + credentials metadata only (no decrypted
         *     secrets ever leave the DB).
         */
        get: operations["data_status_api_system_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle
         * @description Flip a system toggle. `name` ∈ {paused, monitor_paused, llm_enabled};
         *     `enabled` is the new value. The keys live in
         *     strategy_configs.settings_json.
         */
        post: operations["toggle_api_system_toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Homepage state in a single round trip.
         */
        get: operations["summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/morning-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Morning View
         * @description 8 AM ET planning view.
         */
        get: operations["morning_view_api_dashboard_morning_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/active-trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Trades
         * @description All open positions with last monitor evaluation + any pending exit
         *     candidate. Built for the active-trades screen.
         */
        get: operations["active_trades_api_dashboard_active_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Journal
         * @description End-of-day journal for a given date (default: today).
         */
        get: operations["journal_api_dashboard_journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Open an SSE stream of events. The cookie auth is enforced via
         *     middleware + the CurrentUser dependency. Pass `since_id` to resume.
         */
        get: operations["stream_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Credentials
         * @description All configured credentials, metadata only. Always returns a list
         *     (empty when nothing is configured).
         */
        get: operations["list_credentials_api_credentials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{credential_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Credential
         * @description Single credential metadata. 404 when not configured.
         */
        get: operations["get_credential_api_credentials__credential_type__get"];
        /**
         * Upsert Credential Endpoint
         * @description Insert or replace a credential. Body's `secrets` dict is encrypted
         *     before write. The response NEVER echoes the secrets back.
         */
        put: operations["upsert_credential_endpoint_api_credentials__credential_type__put"];
        post?: never;
        /**
         * Delete Credential Endpoint
         * @description Remove the credential row. 404 when not configured (idempotent
         *     callers should check `GET` first or accept 404).
         */
        delete: operations["delete_credential_endpoint_api_credentials__credential_type__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schwab/oauth/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Start
         * @description Start the Schwab OAuth flow.
         *
         *     Reads the user's `schwab_client` (Client ID/Secret) from the encrypted
         *     store and redirects the browser to Schwab's authorize URL with a
         *     Fernet-signed state token.
         */
        get: operations["auth_start_api_schwab_oauth_auth_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schwab/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Receive Schwab's authorization code, exchange for tokens, persist.
         *
         *     Public endpoint (no `CurrentUser` dep): some browsers drop the session
         *     cookie on the cross-site navigation back from schwab.com even with
         *     SameSite=Lax. The state token itself is Fernet-encrypted with our
         *     master key and carries the user_id, so we use it as the sole identity
         *     proof here.
         *
         *     On success, redirects to `/settings/credentials?schwab=connected` so
         *     the UI can show a toast and re-render the card.
         */
        get: operations["callback_api_schwab_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schwab/oauth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Manually trigger a token refresh.
         *
         *     The auto-refresh task in `services/data` runs every 25 min; this is
         *     for the "Refresh now" button on the Credentials page.
         */
        post: operations["refresh_api_schwab_oauth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schwab/oauth/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect
         * @description Remove the `schwab_oauth` credential. `schwab_client` is preserved
         *     so reconnecting only requires another OAuth handshake.
         */
        delete: operations["disconnect_api_schwab_oauth_disconnect_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveTrade */
        ActiveTrade: {
            position: components["schemas"]["PositionSummary"];
            /** Latest Monitor Evaluation */
            latest_monitor_evaluation?: {
                [key: string]: unknown;
            } | null;
            /** Pending Exit Candidate Id */
            pending_exit_candidate_id?: number | null;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /** Notes */
            notes?: string | null;
            /** Quantity Override */
            quantity_override?: number | null;
        };
        /** CandidateActionResponse */
        CandidateActionResponse: {
            /** Id */
            id: number;
            /** New Status */
            new_status: string;
            /** Already Processed */
            already_processed: boolean;
        };
        /** CandidateDetail */
        CandidateDetail: {
            /** Candidate */
            candidate: {
                [key: string]: unknown;
            };
            /** Rule Trace */
            rule_trace?: {
                [key: string]: unknown;
            } | null;
            /** Veto Trace */
            veto_trace?: {
                [key: string]: unknown;
            } | null;
            /** Selected Contract */
            selected_contract?: {
                [key: string]: unknown;
            } | null;
            /** Llm Evaluation */
            llm_evaluation?: {
                [key: string]: unknown;
            } | null;
            /** Lifecycle Events */
            lifecycle_events?: {
                [key: string]: unknown;
            }[];
            /** Copyable Text */
            copyable_text: string;
        };
        /** CandidateSummary */
        CandidateSummary: {
            /** Id */
            id: number;
            /**
             * Candidate Kind
             * @enum {string}
             */
            candidate_kind: "entry" | "exit";
            /** Ticker */
            ticker: string;
            /** Direction */
            direction: string;
            /** Status */
            status: string;
            /** Confidence */
            confidence?: string | null;
            /**
             * Created Ts
             * Format: date-time
             */
            created_ts: string;
            /** Summary Text */
            summary_text: string;
        };
        /**
         * CredentialRecordResponse
         * @description Public-facing credential metadata. NEVER includes secret values.
         */
        CredentialRecordResponse: {
            /**
             * Credential Type
             * @enum {string}
             */
            credential_type: "alpaca_paper" | "alpaca_live" | "schwab_client" | "schwab_oauth" | "finnhub" | "exa" | "mcp_api_key";
            /** Is Configured */
            is_configured: boolean;
            /** Expires At */
            expires_at?: string | null;
            /** Refresh Token Expires At */
            refresh_token_expires_at?: string | null;
            /** Last Used Ts */
            last_used_ts?: string | null;
            /**
             * Created Ts
             * Format: date-time
             */
            created_ts: string;
            /**
             * Updated Ts
             * Format: date-time
             */
            updated_ts: string;
            /** Notes */
            notes?: string | null;
        };
        /** DashboardSummary */
        DashboardSummary: {
            today_watchlist?: components["schemas"]["WatchlistResponse"] | null;
            /** Open Positions Count */
            open_positions_count: number;
            /** Open Positions Total Pnl */
            open_positions_total_pnl?: string | null;
            /** Pending Human Approvals */
            pending_human_approvals: number;
            /** Pending Llm Evaluations */
            pending_llm_evaluations: number;
            /** Recent Events */
            recent_events: {
                [key: string]: unknown;
            }[];
            system_status: components["schemas"]["SystemStatusResponse"];
        };
        /**
         * DataStatusResponse
         * @description `/api/system/data-status` — live state of the market-data layer.
         *
         *     Phase 8a.5. The UI uses this to confirm Schwab is connected, show
         *     expiration warnings, and trigger reauthentication when the rolling
         *     refresh window narrows.
         */
        DataStatusResponse: {
            /**
             * Active Client
             * @enum {string}
             */
            active_client: "mock" | "schwab";
            /** Is Configured */
            is_configured: boolean;
            /** Schwab Oauth Enabled */
            schwab_oauth_enabled: boolean;
            schwab_token_status?: components["schemas"]["SchwabTokenStatus"] | null;
            /** Last Quote Ts */
            last_quote_ts?: string | null;
        };
        /**
         * FullContextResponse
         * @description Lightweight version of CandidateDetail for the 'Copy Full Context'
         *     flow. Returns just the markdown without the structured payload.
         */
        FullContextResponse: {
            /** Copyable Text */
            copyable_text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JournalEntry */
        JournalEntry: {
            /** Date */
            date: string;
            /** Scanner Cycles Run */
            scanner_cycles_run: number;
            /** Candidates Fired */
            candidates_fired: number;
            /** Decisions */
            decisions: {
                [key: string]: number;
            };
            /** Position State Changes */
            position_state_changes: {
                [key: string]: unknown;
            }[];
            /** Pnl Dollars */
            pnl_dollars?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** User */
            user: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Last Login Ts */
            last_login_ts?: string | null;
        };
        /** MorningView */
        MorningView: {
            /** Yesterday Results */
            yesterday_results: {
                [key: string]: unknown;
            };
            today_watchlist?: components["schemas"]["WatchlistResponse"] | null;
            /** Universe */
            universe: string[];
            /** Upcoming Calendar */
            upcoming_calendar: {
                [key: string]: unknown;
            }[];
            /** Pre Market Gaps */
            pre_market_gaps?: {
                [key: string]: unknown;
            }[];
        };
        /** PositionDetail */
        PositionDetail: {
            /** Position */
            position: {
                [key: string]: unknown;
            };
            /** Lifecycle Events */
            lifecycle_events?: {
                [key: string]: unknown;
            }[];
            /** Latest Monitor Evaluation */
            latest_monitor_evaluation?: {
                [key: string]: unknown;
            } | null;
            /** Pending Exit Candidate */
            pending_exit_candidate?: {
                [key: string]: unknown;
            } | null;
        };
        /** PositionSummary */
        PositionSummary: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Contract Symbol */
            contract_symbol: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: number;
            /** Entry Price */
            entry_price: string;
            /**
             * Entry Ts
             * Format: date-time
             */
            entry_ts: string;
            /** Status */
            status: string;
            /** Pnl */
            pnl?: string | null;
            /** Pnl Pct */
            pnl_pct?: string | null;
        };
        /** PromptActivateRequest */
        PromptActivateRequest: {
            /** Version Id */
            version_id: number;
        };
        /** PromptCreateRequest */
        PromptCreateRequest: {
            /**
             * Template Name
             * @enum {string}
             */
            template_name: "entry_evaluation" | "exit_evaluation";
            /** Template Text */
            template_text: string;
            /** Response Schema */
            response_schema: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string | null;
        };
        /** PromptVersionResponse */
        PromptVersionResponse: {
            /** Id */
            id: number;
            /** Template Name */
            template_name: string;
            /** Version Number */
            version_number: number;
            /** Template Text */
            template_text: string;
            /** Response Schema */
            response_schema: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Created Ts
             * Format: date-time
             */
            created_ts: string;
            /** Created By */
            created_by: string;
            /** Activated Ts */
            activated_ts?: string | null;
            /** Deprecated Ts */
            deprecated_ts?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * RefreshResponse
         * @description Manual-refresh API response.
         */
        RefreshResponse: {
            /** Success */
            success: boolean;
            /** Expires At */
            expires_at?: string | null;
            /** Refresh Token Expires At */
            refresh_token_expires_at?: string | null;
            /**
             * Refresh Token Rotated
             * @default false
             */
            refresh_token_rotated: boolean;
            /** Message */
            message: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Notes */
            notes?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SchwabTokenStatus
         * @description Schwab OAuth token expirations exposed to the UI.
         */
        SchwabTokenStatus: {
            /** Access Expires At */
            access_expires_at?: string | null;
            /** Refresh Expires At */
            refresh_expires_at?: string | null;
            /** Refresh Token Hours Remaining */
            refresh_token_hours_remaining?: number | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Settings Json */
            settings_json: {
                [key: string]: unknown;
            };
        };
        /** SettingsUpdateRequest */
        SettingsUpdateRequest: {
            /** Updates */
            updates: {
                [key: string]: unknown;
            };
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Paused */
            paused: boolean;
            /** Monitor Paused */
            monitor_paused: boolean;
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Queue Depth */
            queue_depth: number;
            /** Queue In Flight */
            queue_in_flight: number;
            /** Open Positions */
            open_positions: number;
            /** Pending Human Approvals */
            pending_human_approvals: number;
            /**
             * Trading Mode
             * @default paper
             * @enum {string}
             */
            trading_mode: "paper" | "live";
            /** Override Reasons */
            override_reasons?: {
                [key: string]: string | null;
            };
        };
        /** ToggleRequest */
        ToggleRequest: {
            /**
             * Name
             * @enum {string}
             */
            name: "paused" | "monitor_paused" | "llm_enabled";
            /** Enabled */
            enabled: boolean;
        };
        /** UniverseAddRequest */
        UniverseAddRequest: {
            /** Tickers */
            tickers: string[];
        };
        /** UniverseResponse */
        UniverseResponse: {
            /** Tickers */
            tickers: string[];
        };
        /**
         * UpsertCredentialRequest
         * @description Body for PUT /api/credentials/{type}.
         *
         *     `secrets` is a free-form dict — provider-specific shape (e.g. Alpaca
         *     uses `{api_key, api_secret}`, Finnhub uses `{api_key}`). Validated
         *     server-side per provider in Phase 8b/8c.
         */
        UpsertCredentialRequest: {
            /** Secrets */
            secrets: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /** Date */
            date: string;
            /** Tickers */
            tickers: string[];
            /** Per Ticker Overrides */
            per_ticker_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Notes */
            notes?: string | null;
        };
        /** WatchlistSetRequest */
        WatchlistSetRequest: {
            /** Tickers */
            tickers: string[];
            /** Per Ticker Overrides */
            per_ticker_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Notes */
            notes?: string | null;
            /** Date */
            date?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_candidates_get: {
        parameters: {
            query?: {
                since_hours?: number;
                limit?: number;
                status?: string | null;
                kind?: ("entry" | "exit") | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_full_context_api_candidates__candidate_id__full_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_candidate_api_candidates__candidate_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_candidate_api_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_positions_get: {
        parameters: {
            query?: {
                status?: "open" | "closed" | "all";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_detail_api_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_position_lifecycle_api_positions__position_id__lifecycle_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scanner_evaluations_api_evaluations_scanner_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monitor_evaluations_api_evaluations_monitor_get: {
        parameters: {
            query?: {
                position_id?: number | null;
                hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_evaluations_api_evaluations_llm_get: {
        parameters: {
            query?: {
                candidate_id?: number | null;
                hours?: number;
                limit?: number;
                fallback_only?: boolean;
                decision?: ("STRONG" | "MODERATE" | "WEAK" | "VETO" | "CLOSE" | "CLOSE_PARTIAL" | "HOLD") | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_watchlist_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_today_or_date_api_watchlist_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_ticker_api_watchlist_tickers__ticker__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_ticker_api_watchlist_tickers__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_watchlist_history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_api_universe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniverseAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_universe__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_active_api_prompts__template_name__active_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: string;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_prompts__template_name__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: string;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pending_api_prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_prompts_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptActivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_api_prompts__template_name__rollback__version_number__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: string;
                version_number: number;
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status__api_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_status_api_system_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_api_system_toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    morning_view_api_dashboard_morning_view_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_trades_api_dashboard_active_trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveTrade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    journal_api_dashboard_journal_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_events_stream_get: {
        parameters: {
            query?: {
                since_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRecordResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_credential_api_credentials__credential_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_type: "alpaca_paper" | "alpaca_live" | "schwab_client" | "schwab_oauth" | "finnhub" | "exa" | "mcp_api_key";
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_credential_endpoint_api_credentials__credential_type__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_type: "alpaca_paper" | "alpaca_live" | "schwab_client" | "schwab_oauth" | "finnhub" | "exa" | "mcp_api_key";
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_endpoint_api_credentials__credential_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_type: "alpaca_paper" | "alpaca_live" | "schwab_client" | "schwab_oauth" | "finnhub" | "exa" | "mcp_api_key";
            };
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_start_api_schwab_oauth_auth_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_schwab_oauth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_schwab_oauth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_schwab_oauth_disconnect_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradnex_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
