"""TradNex MCP server admin CLI.

    python -m services.mcp.cli generate-api-key
    python -m services.mcp.cli rotate-api-key
    python -m services.mcp.cli revoke-api-key
    python -m services.mcp.cli show-status
    python -m services.mcp.cli test-connection [--token TOKEN] [--url URL]

API keys are generated with :func:`secrets.token_urlsafe(32)` (~256 bits of
entropy) and stored encrypted in the ``credentials`` table under
``credential_type='mcp_api_key'``. The plaintext value is printed exactly
once — operator must save it immediately.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import secrets
import sys
from datetime import UTC, datetime
from typing import Any

import httpx

from shared.db import get_connection, run_migrations
from shared.services.credentials import (
    delete_credential,
    get_credential_record,
    upsert_credential,
)
from shared.services.encryption import EncryptionService

_API_KEY_BYTES = 32


def _new_api_key() -> str:
    return f"tnx_{secrets.token_urlsafe(_API_KEY_BYTES)}"


def _get_encryption() -> EncryptionService:
    from shared.config import settings

    if not settings.ENCRYPTION_KEY:
        print(
            "ENCRYPTION_KEY is not set. Run `python -m services.api.cli "
            "generate-encryption-key` first.",
            file=sys.stderr,
        )
        sys.exit(2)
    return EncryptionService(settings.ENCRYPTION_KEY)


def _cmd_generate_api_key(args: argparse.Namespace) -> None:
    run_migrations()
    conn = get_connection()
    encryption = _get_encryption()
    try:
        existing = get_credential_record(conn, "mcp_api_key")
        if existing is not None and not args.force:
            print(
                "An mcp_api_key is already configured. Use --force to overwrite, "
                "or `rotate-api-key` for the documented rotation flow.",
                file=sys.stderr,
            )
            sys.exit(2)
        key = _new_api_key()
        upsert_credential(
            conn,
            encryption,
            "mcp_api_key",
            {"api_key": key},
            notes="Generated by services.mcp.cli generate-api-key",
        )
    finally:
        conn.close()
    _print_key_once(key)


def _cmd_rotate_api_key(args: argparse.Namespace) -> None:
    run_migrations()
    conn = get_connection()
    encryption = _get_encryption()
    try:
        key = _new_api_key()
        upsert_credential(
            conn,
            encryption,
            "mcp_api_key",
            {"api_key": key},
            notes=f"Rotated at {datetime.now(UTC).isoformat()}",
        )
    finally:
        conn.close()
    _print_key_once(key, rotated=True)


def _cmd_revoke_api_key(args: argparse.Namespace) -> None:
    run_migrations()
    conn = get_connection()
    try:
        removed = delete_credential(conn, "mcp_api_key")
    finally:
        conn.close()
    if removed:
        print("MCP api key revoked.")
    else:
        print("No mcp_api_key was configured. Nothing to revoke.")


def _cmd_show_status(args: argparse.Namespace) -> None:
    run_migrations()
    conn = get_connection()
    try:
        record = get_credential_record(conn, "mcp_api_key")
    finally:
        conn.close()
    payload: dict[str, Any]
    if record is None:
        payload = {"configured": False}
    else:
        payload = {
            "configured": True,
            "created_ts": record.created_ts.isoformat(),
            "updated_ts": record.updated_ts.isoformat(),
            "last_used_ts": (
                record.last_used_ts.isoformat() if record.last_used_ts else None
            ),
            "notes": record.notes,
        }
    print(json.dumps(payload, indent=2))


async def _cmd_test_connection_async(args: argparse.Namespace) -> None:
    """Send an `initialize` JSON-RPC request to the MCP endpoint."""
    token = args.token
    if not token:
        encryption = _get_encryption()
        conn = get_connection()
        try:
            from shared.services.credentials import get_credential_secrets

            secrets_blob = get_credential_secrets(conn, encryption, "mcp_api_key")
        finally:
            conn.close()
        if not secrets_blob:
            print(
                "No mcp_api_key configured. Pass --token or run `generate-api-key`.",
                file=sys.stderr,
            )
            sys.exit(2)
        token = secrets_blob["api_key"]

    url = args.url
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/json, text/event-stream",
        "Content-Type": "application/json",
    }
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2025-06-18",
            "capabilities": {},
            "clientInfo": {"name": "tradnex-mcp-cli", "version": "0.1"},
        },
    }
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.post(url, headers=headers, json=payload)
    print(f"HTTP {resp.status_code}")
    print(resp.text[:1500])


def _print_key_once(key: str, *, rotated: bool = False) -> None:
    banner = "ROTATED" if rotated else "GENERATED"
    print()
    print("=" * 70)
    print(f"  MCP API KEY {banner} — store this NOW. It will not be shown again.")
    print("=" * 70)
    print()
    print(f"  {key}")
    print()
    print("  Use in Claude.ai MCP connector config as:")
    print(f"      Authorization: Bearer {key}")
    print()
    print("=" * 70)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python -m services.mcp.cli",
        description="TradNex MCP server admin CLI",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate-api-key", help="Create a new MCP API key")
    gen.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing key (use rotate-api-key instead in normal flow)",
    )
    gen.set_defaults(func=_cmd_generate_api_key)

    rot = sub.add_parser("rotate-api-key", help="Replace the existing key with a new one")
    rot.set_defaults(func=_cmd_rotate_api_key)

    rev = sub.add_parser("revoke-api-key", help="Delete the stored MCP API key")
    rev.set_defaults(func=_cmd_revoke_api_key)

    stat = sub.add_parser(
        "show-status", help="Show whether an MCP API key is configured (no secret leakage)"
    )
    stat.set_defaults(func=_cmd_show_status)

    test = sub.add_parser(
        "test-connection",
        help="Send an `initialize` request to the MCP endpoint to verify auth",
    )
    test.add_argument("--token", help="Bearer token; defaults to the stored one")
    test.add_argument(
        "--url",
        default="http://localhost:8090/mcp",
        help="MCP endpoint URL (default: http://localhost:8090/mcp)",
    )
    test.set_defaults(func=lambda a: asyncio.run(_cmd_test_connection_async(a)))

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
